### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [GuyLewin/home-assistant-crunch-o-meter#1]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that, and if you do, mind answering these questions:
- Do you want to enable auto-formatting whenever pushed?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by GuyLewin** [comment]
Hey, sorry for the late reply!
I'd appreciate any help you can offer :)
- I think I'd prefer auto-formatting while developing (as a git hook perhaps) + verification as CI
- Can you elaborate?

**Comment by KTibow** [comment]
> auto-formatting while developing (as a git hook perhaps)

I don't know how to do that.

> Can you elaborate?

Elaborate on what? I usually would add https://github.com/KTibow/ha-blueprint

**Comment by GuyLewin** [comment]
I implemented this myself. Thanks for the offer though!
